### PR TITLE
Bump cryptpad to version 4.5.0

### PR DESCRIPTION
**Pull request by matbgn**
Checked dependencies of alpine image -> all seems fine for a straightforward update

### CODE REVIEW

**Comment by nicholaswilde** [comment]
Thanks for submitting this PR! 🙏🏽 I will take a look.

**Comment by matbgn** [comment]
Thanks to you for your valuable work! Just a dummy question: what stand LS for? e.g. LS=10 I assume it's for versioning but I can get what are each letter for :smile:

**Comment by nicholaswilde** [comment]
Would you mind updating the [checksum](https://github.com/matbgn/docker-cryptpad/blob/75881c08306d9b00c0f9251735ff0dcc7ccf6ca6/Dockerfile#L3) as well for the new package?

**Comment by nicholaswilde** [comment]
> Thanks to you for your valuable work! Just a dummy question: what stand LS for? e.g. LS=10 I assume it's for versioning but I can get what are each letter for 😄

I've modeled my docker images after [linuxserver's](https://github.com/linuxserver) and I _believe_ LS stands for linuxserver. I bump that number when the image is updated and not the app version. 😄

**Comment by matbgn** [comment]
> Would you mind updating the [checksum](https://github.com/matbgn/docker-cryptpad/blob/75881c08306d9b00c0f9251735ff0dcc7ccf6ca6/Dockerfile#L3) as well for the new package?

Course how would I do it for best practice? Any random generator would do the trick for cache invalidation?

**Comment by nicholaswilde** [comment]
> Course how would I do it for best practice? Any random generator would do the trick for cache invalidation?

I use `sha256sum` to check the hash. The easiest way is to use [task](https://taskfile.dev/#/) to generate the checksum after the `task.env` has been updated.

```shell
$ task checksum
```

You can also get a list of task commands by running.

```shell
$ task
```

My [documentation](https://github.com/nicholaswilde/docker-template/wiki/Development) isn't the best, but it's a start.

**Comment by matbgn** [comment]
> My documentation isn't the best, but it's a start.

You're kidding, that wiki, and you're MKDoc are a great starting point!

Checksum updated  :wink:

**Comment by nicholaswilde** [comment]
@matbgn Out of curiosity, which image architecture are you using for Cryptpad? I'm thinking of porting this image over to k8s@home's [container-images](https://github.com/k8s-at-home/container-images) repo but they don't support `armv7`.

**Comment by matbgn** [comment]
Thanks for the question! I use an arm64 architecture. However, out of the nearly 1000 downloads of your image, I'm sure some will be affected. What is the advantage in the end, because the whole process is already automated right? Sorry, professional deformation :-)

**Pull request merged**
